insert into times("nomeTime")
          values('Mousesports'),
                ('North'),
                ('G2 Esports'),
                ('AVANGAR'),
                ('Cr4zy'),
                ('DreamEaters'),
                ('NRG Gaming'),
                ('ForZe'),
                ('Syman Gaming'),
                ('compLexity'),
                ('Grayhound'),
                ('HellRaisers'),
                ('Vitality'),
                ('FURIA'),
                ('INTZ'),
                ('TyLoo')